### PR TITLE
90%: Add Talis error base class

### PR DESCRIPTION
**Pull request by pads**
This change allows library consumers to rescue from all forms of Talis error in one block e.g:

```ruby
rescue Talis::error => error
```

### CODE REVIEW

**Comment by omarqureshi** [comment]
Talis::Errors::Error sounds lame

Worth ditching the Errors namespace? (Please don't hurt me)

**Comment by pads** [comment]
@rsinger this is actually a non-breaking change for Atlas, currently.

**Comment by rsinger** [comment]
Why not make `Talis::Error` a module that can be mix(ed)in, then the errors can potentially inherit from a more focused core/stdlib error, if available (e.g. `Net::HTTPNotFound`)?

**Comment by pads** [comment]
How would that work? You can't rescue from a module as far as I know.

**Comment by rsinger** [comment]
Ok.

**Pull request merged**
