### PR TITLE
90%: Allow and or logic when validating scopes

### PR DESCRIPTION
**Pull request by pads**
This change allows a consumer of the Token class to specify whether or not a given token should contain all wanted scopes or at least one of them.

This helps with talis/atlas-app#28 where a route is scoped to one or another type of user, rather then needing both types.

### CODE REVIEW

**Comment by rsinger** [comment]
I'm not sure I understand the rationale here: is the idea that we have multiple primitives being called in one go (e.g. Blueprint _and_ Babel -- as a completely random pairing) and we can verify the proper scopes at once?

**Comment by rsinger** [comment]
Actually, maybe I do understand now that I've caught up with my email: more for like metatron:read/write?

**Comment by pads** [comment]
This change allows:

`validate(scopes: ['user1_role', 'user2_role'])` where either user is allowed access, rather than both. But only if the `all` flag is false.

By default it allows `['read', 'write']` where both scopes must be present to allow access.

**Comment by rsinger** [comment]
Yeah, that makes sense, now, thanks.

**Comment by rsinger** [comment]
👍

**Pull request merged**
